const participantNames = ['Asmicardo-254','1Junior','Targter','Drayzen254','Reformedbandict7','Nohope'];
const defaultData = { clubs: [...participantNames], fixtures: [], players: [...participantNames], round: 1, matchups: [], completed: [], playerSetVersion: 5 };
const dates = ['Sep 24','Sep 26','Sep 28','Oct 01','Oct 03','Oct 05','Oct 08','Oct 10','Oct 12'];
function readSharedData(){if(!location.hash.startsWith('#state='))return null;try{return JSON.parse(decodeURIComponent(location.hash.slice(7)));}catch(error){return null;}}
let data = readSharedData() || JSON.parse(localStorage.getItem('fixture-room-data') || 'null') || defaultData;
if (data.playerSetVersion !== 5) { data.clubs = [...participantNames]; data.players = [...participantNames]; data.fixtures = makeFixtures(data.clubs); data.round = 1; data.matchups = []; data.completed = []; data.playerSetVersion = 5; save(); }
if (!data.fixtures.length) data.fixtures = makeFixtures(data.clubs);
let selectedFixture = null;
function makeFixtures(clubs){ const list=[]; for(let i=0;i<clubs.length;i+=2){ for(let round=0;round<clubs.length-1;round++){ const home=clubs[(i/2+round)%clubs.length]; const away=clubs[(clubs.length-1-i/2+round)%clubs.length]; if(home!==away) list.push({id:list.length+1,home,away,date:dates[list.length%dates.length],homeScore:null,awayScore:null}); } } return list.slice(0, 12); }
function save(){ localStorage.setItem('fixture-room-data', JSON.stringify(data)); }
function escapeHtml(value){ return String(value).replace(/[&<>'"]/g, char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[char])); }
function standings(){ const table=Object.fromEntries(data.clubs.map(club=>[club,{club,p:0,w:0,d:0,l:0,gf:0,ga:0,pts:0}])); data.fixtures.filter(f=>f.homeScore!==null).forEach(f=>{const h=table[f.home],a=table[f.away]; h.p++;a.p++;h.gf+=f.homeScore;h.ga+=f.awayScore;a.gf+=f.awayScore;a.ga+=f.homeScore;if(f.homeScore>f.awayScore){h.w++;a.l++;h.pts+=3}else if(f.homeScore<f.awayScore){a.w++;h.l++;a.pts+=3}else{h.d++;a.d++;h.pts++;a.pts++}}); return Object.values(table).sort((a,b)=>b.pts-a.pts||(b.gf-b.ga)-(a.gf-a.ga)||b.gf-a.gf); }
function renderStats(){ const played=data.fixtures.filter(f=>f.homeScore!==null).length; const rows=standings(); const leader=rows[0]; document.getElementById('statsGrid').innerHTML=[[''+played,'matches played'],[''+(data.fixtures.length-played),'fixtures remaining'],[leader?.club.split(' ')[0] || '—','UNDISPUTED'],[''+(leader?.pts || 0),'leader points']].map(s=>`<div class="stat"><b>${escapeHtml(s[0])}</b><span>${s[1]}</span></div>`).join(''); }
function renderStandings(){ document.getElementById('standingsBody').innerHTML=standings().map((r,i)=>`<tr><td>${String(i+1).padStart(2,'0')}</td><td>${escapeHtml(r.club)}</td><td>${r.p}</td><td>${r.w}</td><td>${r.d}</td><td>${r.l}</td><td>${r.gf-r.ga>0?'+':''}${r.gf-r.ga}</td><td class="points">${r.pts}</td></tr>`).join(''); }
function fixtureMarkup(f){const done=f.homeScore!==null;return `<div class="fixture-row"><div><div class="fixture-teams">${escapeHtml(f.home)} <span class="muted">vs</span> ${escapeHtml(f.away)}</div><div class="fixture-date">${f.date} · ${done?'Full time':'Upcoming'}</div></div><div class="fixture-score">${done?`${f.homeScore} — ${f.awayScore}`:'—'}</div></div>`}
function renderNext(){document.getElementById('nextFixtures').innerHTML=data.fixtures.filter(f=>f.homeScore===null).slice(0,4).map(fixtureMarkup).join('') || '<p class="muted">All fixtures complete. Start a new season in the Fixtures view.</p>';}
function renderFixtureList(){const played=data.fixtures.filter(f=>f.homeScore!==null).length;document.getElementById('fixtureProgress').textContent=`${played} / ${data.fixtures.length} played`;document.getElementById('fixtureList').innerHTML=data.fixtures.map(f=>`<div class="fixture-item ${selectedFixture===f.id?'selected':''}" data-fixture="${f.id}"><div><div class="fixture-teams">${escapeHtml(f.home)} <span class="muted">vs</span> ${escapeHtml(f.away)}</div><div class="fixture-date">${f.date} · ${f.homeScore===null?'Upcoming':'Full time'}</div></div><div class="fixture-score">${f.homeScore===null?'→':`${f.homeScore} — ${f.awayScore}`}</div></div>`).join('');document.querySelectorAll('[data-fixture]').forEach(el=>el.onclick=()=>selectFixture(Number(el.dataset.fixture)));}
function selectFixture(id){selectedFixture=id;const f=data.fixtures.find(x=>x.id===id);document.getElementById('selectedMatchTitle').textContent=`${f.home} vs ${f.away}`;document.getElementById('selectedMatchMeta').textContent=`${f.date} · Enter the final score`;document.getElementById('homeLabel').textContent=f.home;document.getElementById('awayLabel').textContent=f.away;document.getElementById('homeScore').value=f.homeScore ?? 0;document.getElementById('awayScore').value=f.awayScore ?? 0;document.getElementById('scoreForm').classList.remove('hidden');renderFixtureList();}
function renderMath(){document.getElementById('playerCount').textContent=`${data.players.length} players`;document.getElementById('playerList').innerHTML=data.players.map((p,i)=>`<div class="player-row"><span><span class="player-badge">${escapeHtml(p.slice(0,2).toUpperCase())}</span>${String(i+1).padStart(2,'0')} &nbsp; ${escapeHtml(p)}</span><button class="remove-player" data-remove="${i}" aria-label="Remove ${escapeHtml(p)}">×</button></div>`).join('');document.querySelectorAll('[data-remove]').forEach(el=>el.onclick=()=>{data.players.splice(Number(el.dataset.remove),1);data.matchups=[];save();renderAll();});document.getElementById('roundTitle').textContent=`Round ${String(data.round).padStart(2,'0')}`;if(!data.matchups.length) data.matchups=makeMatchups();document.getElementById('roundHint').textContent=data.players.length<2?'Add at least two players to generate matchups.':'Pairs are rotated each time you start a new round.';document.getElementById('matchupList').innerHTML=data.players.length<2?'<p class="muted">Waiting for more players.</p>':data.matchups.map((m,i)=>`<div class="matchup ${data.completed.includes(i)?'completed':''}"><span class="matchup-number">${String(i+1).padStart(2,'0')}</span><span class="matchup-name"><span class="player-badge">${escapeHtml(m[0].slice(0,2).toUpperCase())}</span>${escapeHtml(m[0])}</span><span class="matchup-vs">vs</span><span class="matchup-name"><span class="player-badge">${escapeHtml((m[1] || 'BY').slice(0,2).toUpperCase())}</span>${escapeHtml(m[1] || 'BYE')}</span><input type="checkbox" data-complete="${i}" ${data.completed.includes(i)?'checked':''}></div>`).join('');document.querySelectorAll('[data-complete]').forEach(el=>el.onchange=()=>{const i=Number(el.dataset.complete);if(el.checked)data.completed.push(i);else data.completed=data.completed.filter(x=>x!==i);save();renderMath();});}
function makeMatchups(){const shift=(data.round-1)%data.players.length;const list=[...data.players.slice(shift),...data.players.slice(0,shift)];const pairs=[];while(list.length>1)pairs.push([list.shift(),list.pop()]);if(list.length)pairs.push([list[0],'BYE']);return pairs;}
function renderAll(){renderStats();renderStandings();renderNext();renderFixtureList();renderMath();}
function toast(message){const el=document.getElementById('toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200);}
document.querySelectorAll('[data-view]').forEach(button=>button.onclick=()=>{const view=button.dataset.view;document.querySelectorAll('.view').forEach(el=>el.classList.toggle('active-view',el.id===`${view}View`));document.querySelectorAll('.nav-item').forEach(el=>el.classList.toggle('active',el.dataset.view===view));});
document.getElementById('saveResult').onclick=()=>{if(selectedFixture===null)return;const f=data.fixtures.find(x=>x.id===selectedFixture);f.homeScore=Number(document.getElementById('homeScore').value);f.awayScore=Number(document.getElementById('awayScore').value);save();renderAll();toast('Result saved. Table updated.');};
document.getElementById('clearResult').onclick=()=>{const f=data.fixtures.find(x=>x.id===selectedFixture);f.homeScore=null;f.awayScore=null;save();renderAll();toast('Result cleared.');};
document.getElementById('addPlayer').onclick=()=>{const input=document.getElementById('playerInput');const name=input.value.trim();if(name&&!data.players.includes(name)){data.players.push(name);data.matchups=[];input.value='';save();renderAll();toast(`${name} added to the league.`);}};
document.getElementById('playerInput').onkeydown=e=>{if(e.key==='Enter')document.getElementById('addPlayer').click()};
document.getElementById('nextRound').onclick=()=>{if(data.players.length<2)return toast('Add at least two players first.');data.round++;data.matchups=[];data.completed=[];save();renderMath();toast('New matchups generated.');};
document.getElementById('shareUpdate').onclick=async()=>{const url=`${location.href.split('#')[0]}#state=${encodeURIComponent(JSON.stringify(data))}`;try{await navigator.clipboard.writeText(url);toast('Share link copied.');}catch(error){prompt('Copy this share link:',url);}};
document.getElementById('resetData').onclick=()=>{if(confirm('Reset all saved results and players?')){data=JSON.parse(JSON.stringify(defaultData));data.fixtures=makeFixtures(data.clubs);selectedFixture=null;save();renderAll();toast('Workspace reset.');}};
renderAll();